data:
  type: eurosat
  # size: 224
  oversample: 1.0
  img_dir: 'EURO_TRAIN'
  mean: [0.368, 0.381, 0.3436]
  std: [0.2035, 0.1854, 0.1849]
  # actual mean/std, but imagenet numbers work a bit better
  # mean: [0.3916, 0.3936, 0.3658]
  # std: [0.2775, 0.2713, 0.2751]
  vis_factor: 1.0
  base_resolution: 2.5
  