data:
  type: fmow
  # size: 224
  oversample: 1.0
  img_dir: 'fdata/train'
  mean: [0.485, 0.456, 0.406] 
  std: [0.229, 0.224, 0.225]  
  # actual mean/std, but imagenet numbers work a bit better
  # mean: [0.3916, 0.3936, 0.3658]
  # std: [0.2775, 0.2713, 0.2751]
  vis_factor: 1.0
  base_resolution: 2.5
  